Feature/footer
peaksoft-school/gadgetarium-js8 pull request #10
Opened 2023-04-09 19:58 UTC by Nurbolot00

2023-04-10 02:55 UTC, FeruzaKazakova approved these changes

2023-04-10 02:55 UTC, FeruzaKazakova commented on src/components/footer/Footer.tsx
>  }
no comments

2023-04-10 04:40 UTC, myktybek03 approved these changes

2023-04-10 05:56 UTC, Nurzada03 approved these changes

2023-04-11 10:37 UTC, songhee24 approved these changes

2023-04-11 10:43 UTC, songhee24 requested changes

2023-04-11 10:43 UTC, songhee24 commented on src/components/footer/Footer.tsx
> +import { ReactComponent as Telephone } from '../../assets/icons/telephoneIcon.svg'
<img width="616" alt="Screenshot 2023-04-11 at 16 40 14" src="https://user-images.githubusercontent.com/44497623/231136451-81ba5109-b5c4-4252-b370-0ba912c402f3.png">
шрифты не те 
по дизайну
<img width="837" alt="Screenshot 2023-04-11 at 16 41 24" src="https://user-images.githubusercontent.com/44497623/231136644-1d926fe0-68c6-4357-82d9-370b949ae737.png">

2023-04-11 10:43 UTC, songhee24 commented on src/components/footer/Footer.tsx
> +import { ReactComponent as Telephone } from '../../assets/icons/telephoneIcon.svg'
у тебя чет все слиплось 
<img width="438" alt="Screenshot 2023-04-11 at 16 41 58" src="https://user-images.githubusercontent.com/44497623/231136745-bb3b29d4-9c9a-42f3-a786-8cb2f4a95ad6.png">

тут по другому
<img width="556" alt="Screenshot 2023-04-11 at 16 42 49" src="https://user-images.githubusercontent.com/44497623/231136924-ce43ec04-3203-4b87-a32e-35d3d68517b9.png">

2023-04-11 10:58 UTC, songhee24 approved these changes

2023-04-11 10:59 UTC, merged