header was completed
peaksoft-school/gadgetarium-js8 pull request #11
Opened 2023-04-10 05:25 UTC by FeruzaKazakova

2023-04-10 05:35 UTC, Nurbolot00 approved these changes

2023-04-10 05:36 UTC, myktybek03 approved these changes

2023-04-10 05:50 UTC, Nurzada03 approved these changes

2023-04-11 10:35 UTC, songhee24 requested changes

2023-04-11 10:35 UTC, songhee24 commented on src/components/header/Header.tsx
> +            </li>
зачем еще li

2023-04-11 10:35 UTC, songhee24 commented on src/components/header/Header.tsx
> +  'li:first-child': {
":first-child" не стоит использовать используйте ":first-of-type

2023-04-11 10:35 UTC, songhee24 commented on src/components/header/Header.tsx
> +    'span:nth-child(2)': {
тоже вместо nth-child лучше   :nth-of-type.

2023-04-11 10:35 UTC, songhee24 requested changes

2023-04-11 10:35 UTC, songhee24 commented on src/components/header/Header.tsx
> +import { ReactComponent as UnionIcon } from '../../assets/icons/header-icons/unionIcon.svg'
<img width="491" alt="Screenshot 2023-04-11 at 16 35 13" src="https://user-images.githubusercontent.com/44497623/231135261-166674b7-5df2-4b23-8fa6-9dad30261414.png">

2023-04-11 10:35 UTC, songhee24 commented on src/components/header/Header.tsx
> +import { ReactComponent as UnionIcon } from '../../assets/icons/header-icons/unionIcon.svg'
шрифты не подключены

2023-04-11 11:19 UTC, songhee24 approved these changes

2023-04-11 11:19 UTC, merged