Feature/contacts
peaksoft-school/gadgetarium-js8 pull request #16
Opened 2023-04-13 09:40 UTC by Nurzada03

2023-04-13 12:02 UTC, myktybek03 approved these changes

2023-04-13 12:12 UTC, dilmuratsarybaev approved these changes

2023-04-14 01:08 UTC, Nurbolot00 approved these changes

2023-04-14 07:31 UTC, songhee24 requested changes

2023-04-14 07:31 UTC, songhee24 commented on src/layout/contacts/Contackt.tsx
> +export default Contackts
нужно удалить яндекс библиотеку

2023-04-14 07:43 UTC, merged