Feature/accordion
peaksoft-school/gadgetarium-js8 pull request #17
Opened 2023-04-14 09:32 UTC by myktybek03

2023-04-14 10:10 UTC, FeruzaKazakova commented on src/layout/user/FrequentlyAskedQuestions.tsx
> +export default FrequentlyAskedQuestions
кажется есть конфликты try to solve the problem

2023-04-14 10:27 UTC, FeruzaKazakova approved these changes

2023-04-14 10:27 UTC, FeruzaKazakova commented on src/layout/user/FrequentlyAskedQuestions.tsx
> +}
no comments

2023-04-14 10:57 UTC, Nurzada03 approved these changes

2023-04-14 16:15 UTC, dilmuratsarybaev approved these changes

2023-04-17 10:28 UTC, songhee24 requested changes

2023-04-17 10:28 UTC, songhee24 commented on src/assets/icons/CheckIcon.svg
icon is not component please change the name to checkIcon

2023-04-17 10:28 UTC, songhee24 commented on src/assets/icons/CheckIcon.svg
also change it everywhere

2023-04-17 10:51 UTC, songhee24 approved these changes

2023-04-17 10:51 UTC, merged