Feature/preview slider
peaksoft-school/gadgetarium-js8 pull request #18
Opened 2023-04-15 11:27 UTC by FeruzaKazakova

2023-04-15 11:39 UTC, myktybek03 approved these changes

2023-04-16 10:03 UTC, Nurzada03 approved these changes

2023-04-16 13:05 UTC, dilmuratsarybaev approved these changes

2023-04-17 11:59 UTC, songhee24 requested changes

2023-04-17 11:59 UTC, songhee24 commented on src/components/UI/preview-slider/PreviewSlider.tsx
> +  'https://s3-alpha-sig.figma.com/img/622d/475f/b660f75948ea28245fbc0f630ba4dfd1?Expires=1682294400&Signature=UDZleFrxKO99C-PKPUqxT~przzwMAUKZz3c906rWmlCIwQIRy9wN6pZr2Yh8eRBlMTyrdZe0LfdbukDRMjaYlJYyW
too bad idea

2023-04-17 11:59 UTC, songhee24 commented on src/components/UI/preview-slider/PreviewSlider.tsx
> +        {images.map((image) => (
please use props instead

2023-04-17 12:25 UTC, songhee24 approved these changes

2023-04-17 12:25 UTC, merged