complated feedbacks
peaksoft-school/gadgetarium-js8 pull request #19
Opened 2023-04-16 09:51 UTC by Nurzada03

2023-04-16 10:15 UTC, FeruzaKazakova approved these changes

2023-04-16 10:15 UTC, FeruzaKazakova commented on src/components/UI/feedbacks/SuccessfulRequest.tsx
> +}
no comments

2023-04-16 10:46 UTC, myktybek03 approved these changes

2023-04-16 13:13 UTC, dilmuratsarybaev commented on src/components/UI/feedbacks/Ratings.tsx
> +        <MainContainer>
MainContainer at eki jolu  jazilip kalganby

2023-04-17 04:38 UTC, Nurzada03 commented on src/components/UI/feedbacks/Ratings.tsx
> +        <MainContainer>
fexed

2023-04-17 05:45 UTC, dilmuratsarybaev approved these changes

2023-04-18 09:52 UTC, songhee24 requested changes

2023-04-18 09:52 UTC, songhee24 commented on src/assets/icons/CameraIcon.svg
file icon name should start with lowercase

2023-04-18 09:52 UTC, songhee24 commented on src/components/UI/feedbacks/Feedback.tsx
> +    <Container>
когда вы в бекенд чо то отправляете ваша компоненты должна быть формой

2023-04-18 09:52 UTC, songhee24 commented on src/components/UI/feedbacks/Feedback.tsx
> +      <StyledTitle>Оставьте свой отзыв</StyledTitle>
<img width="304" alt="Screenshot 2023-04-18 at 15 49 56" src="https://user-images.githubusercontent.com/44497623/232740306-e5ea7992-0a71-4314-9906-9d58c97bd931.png">
плюс это модалка я не вижу чтобы через пропсы можно было бы его открывать и закрывать получать оттуда веденные данные и так далее

2023-04-18 09:52 UTC, songhee24 commented on src/components/UI/feedbacks/SuccessfulRequest.tsx
> +  const [openModal, setOpenModal] = useState<boolean>(false)
не правильно модалка должна вызывать извне а не внутри

2023-04-18 09:52 UTC, songhee24 commented on src/components/UI/feedbacks/SuccessfulRequest.tsx
> +      <Button onClick={ModalHandler}>Open Modal</Button>
уберите эту кнопку

2023-04-19 06:02 UTC, songhee24 approved these changes

2023-04-19 06:42 UTC, merged