Feature/modal
peaksoft-school/gadgetarium-js8 pull request #2
Opened 2023-04-05 15:55 UTC by Nurzada03

2023-04-07 06:30 UTC, Nurbolot00 requested changes

2023-04-07 06:30 UTC, Nurbolot00 commented on src/index.tsx
> +    <BrowserRouter>
азырынча BrowserRouter керек эмес го деп ойлойм

2023-04-07 06:30 UTC, Nurbolot00 commented on src/components/UI/Modal.tsx
> +type Props1 = {
Название типа для пропса надо понятнее писать мне кажется, чтобы потом не путать

2023-04-07 06:30 UTC, Nurbolot00 commented on src/components/UI/Modal.tsx
> +  children?: string
Через пропс может прийти не только string ведь, вроде тип JSX Element надо дать

2023-04-07 07:07 UTC, Nurbolot00 approved these changes

2023-04-07 07:07 UTC, FeruzaKazakova approved these changes

2023-04-07 07:07 UTC, FeruzaKazakova commented on src/index.tsx
everything is ok

2023-04-07 10:14 UTC, dilmuratsarybaev approved these changes

2023-04-07 11:09 UTC, songhee24 requested changes

2023-04-07 11:09 UTC, songhee24 commented on src/components/UI/Modal.tsx
> +  left: 'calc(50% -  20rem)'
опасные расчеты нужно делать относительно от экранов по 50% и все

2023-04-07 11:09 UTC, songhee24 commented on src/components/UI/Modal.tsx
> +  left: 'calc(50% -  20rem)'
через transforms

2023-04-07 11:09 UTC, songhee24 commented on src/components/UI/Modal.tsx
> +        <Box>
а зачем еще излишние вложеность ?

2023-04-07 11:09 UTC, songhee24 commented on src/components/UI/Modal.tsx
> +  position: 'fixed',
absolute лучше использовать

2023-04-07 12:08 UTC, songhee24 requested changes

2023-04-07 12:08 UTC, songhee24 commented on src/components/UI/Modal.tsx
> +        <Box>
<Box> какую роль выполняет ?

2023-04-08 14:16 UTC, songhee24 requested changes

2023-04-08 14:16 UTC, songhee24 commented on src/components/UI/Modal.tsx
> +  )
![Screenshot 2023-04-08 at 20 15 59](https://user-images.githubusercontent.com/44497623/230725966-e8748bba-4c35-468e-b60e-f52499f4cd88.png)
для чего нам оборачивать в Box

2023-04-09 11:27 UTC, merged