Feature/card
peaksoft-school/gadgetarium-js8 pull request #20
Opened 2023-04-16 12:57 UTC by dilmuratsarybaev

2023-04-17 04:55 UTC, Nurzada03 approved these changes

2023-04-17 05:46 UTC, FeruzaKazakova approved these changes

2023-04-17 05:53 UTC, myktybek03 approved these changes

2023-04-18 10:29 UTC, songhee24 commented on src/assets/icons/EllipseIcon.svg
название иконок пишите lowercase

2023-04-18 10:29 UTC, songhee24 commented on src/assets/icons/EllipseIcon.svg
ВСЕХ иконок

2023-04-18 10:29 UTC, songhee24 commented on src/assets/icons/product-icons/starEmpty.svg
если есть большие иконки исправьте

2023-04-18 10:29 UTC, songhee24 commented on src/components/card/ProductCard.tsx
> +    <CardContainer>
<img width="388" alt="Screenshot 2023-04-18 at 16 02 08" src="https://user-images.githubusercontent.com/44497623/232743602-b8610d8d-7924-425f-ac7a-5de8b6ae2114.png">
длинный текст должен быть обрезан

2023-04-18 10:29 UTC, songhee24 commented on src/components/card/ProductCard.tsx
> +    <div>
почему две части иконки ? можно одну только взять

2023-04-18 10:33 UTC, songhee24 requested changes

2023-04-18 10:33 UTC, songhee24 commented on src/components/card/ProductCard.tsx
> +      <LikeIconDetail />
почему две части иконки ? можно одну только взять

2023-04-18 10:33 UTC, songhee24 commented on src/components/card/ProductCard.tsx
> +          <StyledStartIconsContainer>
здесь нужна библиотека или y mui тоже есть рейтйинг библитека потому что значение рейтинга будет приходить из пропса значит из бека и смотря на этот рейтинг нужно заполнят звездочками

2023-04-18 10:33 UTC, songhee24 commented on src/components/card/ProductCard.tsx
> +        <ContainerTwoIcons>
это тоже кликабельные значит им тоже функции нужны

2023-04-19 05:34 UTC, songhee24 requested changes

2023-04-19 05:34 UTC, songhee24 commented on src/components/card/RatingProduct.tsx
> +const ProductRating = ({ rating, totalRating }: Props) => {
<img width="471" alt="Screenshot 2023-04-19 at 11 31 34" src="https://user-images.githubusercontent.com/44497623/232975795-54fa181d-ed2f-49bf-8123-e3f6ae40c2fc.png">
этот рейтинг не кликабельный он просто для чтения

2023-04-19 05:34 UTC, songhee24 commented on src/components/card/ProductCard.tsx
> +          <StyledIconButton icon={<ScaleIcon />} />
им тоже нужны функции для контроля

2023-04-19 07:32 UTC, songhee24 requested changes

2023-04-19 07:32 UTC, songhee24 commented on src/components/card/RatingProduct.tsx
> +  const [value, setValue] = React.useState<number | null>(rating)
убери это

2023-04-19 07:32 UTC, songhee24 commented on src/components/card/RatingProduct.tsx
> +          setValue(newValue)
это тоже не нужно

2023-04-19 08:14 UTC, songhee24 approved these changes

2023-04-19 08:15 UTC, merged