Feature/sign in sign up layout
peaksoft-school/gadgetarium-js8 pull request #21
Opened 2023-04-17 11:31 UTC by Nurbolot00

2023-04-18 07:04 UTC, FeruzaKazakova approved these changes

2023-04-18 10:29 UTC, myktybek03 approved these changes

2023-04-18 11:12 UTC, dilmuratsarybaev approved these changes

2023-04-19 05:52 UTC, songhee24 requested changes

2023-04-19 05:52 UTC, songhee24 commented on src/layout/signin-signup/SignIn.tsx
> +        width: '100%',
разве тебе eslint warning не дал ? что inline нельзя писать

2023-04-19 05:52 UTC, songhee24 commented on src/layout/signin-signup/SignIn.tsx
> +    <div
компонента логина и пароля в особенности должна быть формой

2023-04-19 05:52 UTC, songhee24 commented on src/layout/signin-signup/SignUp.tsx
> +const SignUp = () => {
<img width="402" alt="Screenshot 2023-04-19 at 11 47 43" src="https://user-images.githubusercontent.com/44497623/232978295-37da9c0c-78e0-4fa4-9f4d-4edd04020ad4.png">
смотри это модалка по середине страницы

2023-04-19 05:52 UTC, songhee24 commented on src/layout/signin-signup/SignUp.tsx
> +const SignUp = () => {
то есть есть отдельно модалка которая если открыта как страница то не закрывается.

2023-04-19 05:52 UTC, songhee24 commented on src/layout/signin-signup/SignUp.tsx
> +const SignUp = () => {
<img width="499" alt="Screenshot 2023-04-19 at 11 49 08" src="https://user-images.githubusercontent.com/44497623/232978560-10711433-8db7-4276-b88a-0a1eb09746f1.png">
но иногда должна быть использована как реальная модалка которая в последующем будет закрываться

2023-04-25 06:24 UTC, songhee24 requested changes

2023-04-25 06:24 UTC, songhee24 commented on src/components/UI/modals/SignInModal.tsx
> +          <StyledModalForm action="">
submit должен быть

2023-04-25 06:24 UTC, songhee24 commented on src/layout/signin-signup/SignIn.tsx
давай не layout а containers папку

2023-04-26 08:17 UTC, songhee24 approved these changes

2023-04-26 08:17 UTC, merged