reusable_Table
peaksoft-school/gadgetarium-js8 pull request #24
Opened 2023-04-23 06:28 UTC by Nurzada03

2023-04-23 08:34 UTC, myktybek03 approved these changes

2023-04-23 21:47 UTC, Nurbolot00 approved these changes

2023-04-25 14:12 UTC, FeruzaKazakova approved these changes

2023-04-26 17:09 UTC, Nurbolot00 approved these changes

2023-04-27 06:59 UTC, songhee24 requested changes

2023-04-27 06:59 UTC, songhee24 commented on src/components/UI/table/TableList.tsx
> +const AppTable = <T,>({ columns, rows }: Props<T>) => {
я должен иметь возможность получить айди отмеченных чекбоксов иначе тейбл не будет reusable

2023-04-27 11:54 UTC, songhee24 approved these changes

2023-04-27 11:54 UTC, merged