categories
peaksoft-school/gadgetarium-js8 pull request #25
Opened 2023-04-23 08:56 UTC by myktybek03

2023-04-23 09:23 UTC, FeruzaKazakova approved these changes

2023-04-24 04:34 UTC, Nurzada03 approved these changes

2023-04-24 04:45 UTC, Nurbolot00 approved these changes

2023-04-25 03:59 UTC, dilmuratsarybaev approved these changes

2023-04-25 07:29 UTC, songhee24 commented on src/components/UI/Categories.tsx
> +                  <TitleStyled key={item.title}>{item.title}</TitleStyled>
какой то category тандасам ал тандалып жабылыш керек плюс танданлагн элементин айдисин алып бериш керек башка компонентке

2023-04-25 07:29 UTC, songhee24 commented on src/components/UI/Categories.tsx
> +        {test &&
опасный оператор лучше испоьзовать condition ? var : var2

2023-04-25 07:31 UTC, songhee24 requested changes

2023-04-25 07:31 UTC, songhee24 commented on src/components/UI/Categories.tsx
> +const Categories = () => {
плюс данные должны приходить извне как пропс

2023-04-25 07:31 UTC, songhee24 commented on src/components/UI/Categories.tsx
> +              {categori.menuItem.map((item) => (
какой то category тандасам ал тандалып жабылыш керек плюс танданлагн элементин айдисин алып бериш керек башка компонентке

2023-04-25 07:31 UTC, songhee24 commented on src/components/UI/Categories.tsx
> +          [test].map((categori) => (
опасный оператор лучше испоьзовать condition ? var : var2

2023-04-26 08:10 UTC, songhee24 approved these changes

2023-04-26 08:10 UTC, merged