adding routes
peaksoft-school/gadgetarium-js8 pull request #26
Opened 2023-04-24 07:34 UTC by FeruzaKazakova

2023-04-24 07:51 UTC, myktybek03 approved these changes

2023-04-24 07:52 UTC, myktybek03 approved these changes

2023-04-24 14:00 UTC, Nurzada03 approved these changes

2023-04-25 03:56 UTC, dilmuratsarybaev approved these changes

2023-04-27 07:33 UTC, songhee24 commented on src/routes/MainRoutes.tsx
> +      <Routes>
было бы хорошо все пути использовать как константы

2023-04-27 07:33 UTC, songhee24 commented on src/routes/MainRoutes.tsx
> +          element={<ProtectedRoute isAllowed={[roles.user]} component={() => <p>UserPage</p>} />}
и да не совсем понимаю логику isAllowed если логически посмотреть пропс назван будто проверяет юзер зарегался или нет 
а для ролей я бы дал другой проп допустим roles

2023-04-27 07:33 UTC, songhee24 commented on src/routes/private/ProtectedRoute.tsx
> +const ProtectedRoute = ({ component: Component, isAllowed }: ProtectedRouteProps) => {
я бы еще поставил бы проверку на то что он авторизован или нет если нет navigate to login or как раз в ващем случае показывал бы модалку для авторизации

2023-04-27 07:37 UTC, songhee24 requested changes
в целом мне нравится структура дизайна 
но вот несколько вещей меня беспокоят

2023-04-27 07:37 UTC, songhee24 commented on src/routes/private/ProtectedRoute.tsx
> +const ProtectedRoute = ({ component: Component, isAllowed }: ProtectedRouteProps) => {
я бы еще поставил бы проверку на то что он авторизован или нет если нет navigate to login or как раз в ващем случае показывал бы модалку для авторизации

2023-04-27 12:26 UTC, songhee24 approved these changes

2023-04-27 12:26 UTC, merged