sign-in/sign-up integration
peaksoft-school/gadgetarium-js8 pull request #29
Opened 2023-05-01 09:13 UTC by Nurbolot00

2023-05-01 09:19 UTC, FeruzaKazakova approved these changes

2023-05-01 09:30 UTC, Nurzada03 approved these changes

2023-05-01 10:07 UTC, myktybek03 approved these changes

2023-05-01 10:36 UTC, dilmuratsarybaev approved these changes

2023-05-01 10:38 UTC, songhee24 requested changes

2023-05-01 10:38 UTC, songhee24 commented on src/App.tsx
> +          <AppContent />
регистрация закончена как я вижу 
теперь нужно добавить взаимодействие с роутерами
после того как прошел регистрация делать редирект

2023-05-01 10:39 UTC, songhee24 commented on src/App.tsx
> +          <AppContent />
app routes нужно вызвать и проверять защищенные роуты

2023-05-03 12:23 UTC, songhee24 requested changes

2023-05-03 12:23 UTC, songhee24 commented on src/components/UI/modals/SignUpModal.tsx
> +      .catch((e) => setSignUpError(e.response.data.message))
не вижу смысла использовать setSignUpError 
ты же его можешь получить через store

2023-05-03 12:23 UTC, songhee24 commented on src/components/UI/modals/SignUpModal.tsx
> +      .catch((e) => setSignUpError(e.response.data.message))
когда статус  signIn.rejected ты же уже используешь эту логику

2023-05-03 12:23 UTC, songhee24 commented on src/App.tsx
>    return <div></div>
и да как я понимаю в вашем приложении нужно внутри AppContent вызывать AppRoutes

2023-05-04 09:26 UTC, songhee24 requested changes

2023-05-04 09:26 UTC, songhee24 commented on src/components/UI/modals/SignInModal.tsx
> +            Нет аккаунта? <a href="/signup">Зарегистрироваться</a>
wow tag <a> запрещено использовать лучше Link

2023-05-04 09:26 UTC, songhee24 commented on src/components/UI/modals/SignUpModal.tsx
> +            Уже есть аккаунт? <a href="/login">Войти</a>
also here

2023-05-04 09:32 UTC, songhee24 approved these changes

2023-05-04 09:32 UTC, merged