completed mailingList
peaksoft-school/gadgetarium-js8 pull request #30
Opened 2023-05-03 05:23 UTC by Nurzada03

2023-05-03 06:07 UTC, myktybek03 approved these changes

2023-05-03 06:38 UTC, FeruzaKazakova approved these changes

2023-05-03 06:40 UTC, dilmuratsarybaev approved these changes

2023-05-03 10:38 UTC, songhee24 requested changes

2023-05-03 10:38 UTC, songhee24 commented on src/redux/store/mailingList/mailingList.thunk.ts
> +export const postMailingList = createAsyncThunk(
postMailingList если вы хотите использовать через unwrap то можно и не добавлять extraReducers: () => {} плюс ваши   errors: {
    message: null
  },
  isLoading: '',
  promiseMessage: null вообще не нужны 
  а если вы думаете что extraReducers нужны то прошу реализовывать полностью

2023-05-03 10:38 UTC, songhee24 commented on src/hooks/useUploadAvatar.tsx
почему он находится внутри папки hooks ?

2023-05-03 10:38 UTC, songhee24 commented on src/hooks/useUploadAvatar.tsx
это разве хук ?

2023-05-03 10:38 UTC, songhee24 commented on src/hooks/useUploadAvatar.tsx
> +const ImagePicker: FC<ImagePickerProps> = ({ onSelectImage }) => {
и да раз вы решили самой сделать загрузку изображений прошу посмотреть во всех местах логику загрузки фотографии и сделать так чтобы ваша функция которая отвечает за получение фоток 
была доступна всем как глобальная функция

2023-05-03 10:38 UTC, songhee24 commented on src/components/admin/UI/MailingList.tsx
> +    const newData = {
добавьте хотя бы проверку на то чтобы поля не были пустыми

2023-05-04 05:19 UTC, songhee24 requested changes

2023-05-04 05:19 UTC, songhee24 commented on src/components/admin/UI/mailingList/ImagePicker.tsx
> +  const handleImageChange = (e: ChangeEvent<HTMLInputElement>) => {
создайте кастомный хук который позволяет получить фотографии

2023-05-04 05:19 UTC, songhee24 commented on src/components/admin/UI/mailingList/ImagePicker.tsx
> +  const handleImageChange = (e: ChangeEvent<HTMLInputElement>) => {
то есть вынесите эту функцию за пределы компонентов чтобы все кто будут работать с фотками имел доступ использовать вашу логику

2023-05-04 05:19 UTC, songhee24 commented on src/components/admin/UI/mailingList/MailingList.tsx
> +const MailingList = ({ modalHandler, modal }: Props) => {
мы можем назвать компоненту CreateMailingList  ?

2023-05-04 11:56 UTC, songhee24 approved these changes

2023-05-04 11:56 UTC, merged