create-discount
peaksoft-school/gadgetarium-js8 pull request #31
Opened 2023-05-03 06:20 UTC by myktybek03

2023-05-03 06:41 UTC, dilmuratsarybaev approved these changes

2023-05-18 06:58 UTC, FeruzaKazakova approved these changes

2023-05-18 07:09 UTC, Nurzada03 approved these changes

2023-05-18 07:09 UTC, Nurzada03 commented on src/components/discount/CreateDiscount.tsx
> +  const [openModal, setOpenModal] = useState(false)
openModal,setOpenModal need to come in the props

2023-05-19 09:15 UTC, songhee24 requested changes

2023-05-19 09:15 UTC, songhee24 commented on src/components/discount/CreateDiscount.tsx
> +      <Modalka open={open} onClose={onClose}>
Modalka что за название ?

2023-05-19 09:15 UTC, songhee24 commented on src/components/discount/CreateDiscount.tsx
> +            <InputStyled
![Screenshot 2023-05-19 at 15 11 32](https://github.com/peaksoft-school/gadgetarium-js8/assets/44497623/3f00df78-b84d-441f-ae7d-ea2e873a6a05)

2023-05-19 09:15 UTC, songhee24 commented on src/components/discount/CreateDiscount.tsx
> +            <InputStyled
0 не могу убрать постоянно стоит

2023-05-19 09:15 UTC, songhee24 commented on src/components/admin/UI/table/Table.tsx
> +  collectSelectedIds,
![Screenshot 2023-05-19 at 15 14 18](https://github.com/peaksoft-school/gadgetarium-js8/assets/44497623/651b6ac4-8f8d-464c-aeb8-2c9cbb09a883)
скидка берип буткондон кийин товар uncheck болуш керек

2023-05-22 07:09 UTC, songhee24 approved these changes

2023-05-22 07:09 UTC, merged