Feature/add banner
peaksoft-school/gadgetarium-js8 pull request #34
Opened 2023-05-08 13:38 UTC by dilmuratsarybaev

2023-05-09 20:49 UTC, FeruzaKazakova approved these changes

2023-05-11 10:35 UTC, Nurzada03 approved these changes

2023-05-11 10:35 UTC, Nurzada03 approved these changes

2023-05-11 10:37 UTC, Nurbolot00 approved these changes

2023-05-15 07:51 UTC, songhee24 requested changes

2023-05-15 07:51 UTC, songhee24 commented on src/components/admin/UI/banners/Banner.tsx
> +        dispatch(bannerAction.addItemImage(imageUrl))
![Screenshot 2023-04-29 at 13 46 47](https://github.com/peaksoft-school/gadgetarium-js8/assets/44497623/72c722c0-0990-4510-8432-5d4df27854d2)
запрос должен отправляться только после того как нажали на кнопку "Загрузить"

2023-05-15 07:51 UTC, songhee24 commented on src/components/admin/UI/banners/Banner.tsx
> +        dispatch(bannerAction.addItemImage(imageUrl))
и да зачем тебе отправлять запрос через стор сделай через обычные сервисы не локально

2023-05-15 07:51 UTC, songhee24 commented on src/components/admin/UI/banners/Banner.tsx
> +    dispatch(bannerAction.deleteImageAll([]))
не придется удалять все фотки если ты будешь загружать только после того как нажали кнопку 
"Загрузить"

2023-05-16 13:42 UTC, songhee24 approved these changes

2023-05-16 13:42 UTC, songhee24 commented on src/hooks/banner/useBanner.ts
> +  const postRequestBanner = async () => {
yess that’s all

2023-05-16 13:42 UTC, merged