Feature/admin products
peaksoft-school/gadgetarium-js8 pull request #35
Opened 2023-05-10 13:15 UTC by FeruzaKazakova

кажется fixing будет длиться вечно

2023-05-12 04:47 UTC, Nurzada03 approved these changes

2023-05-12 04:47 UTC, Nurzada03 approved these changes

2023-05-12 05:39 UTC, myktybek03 approved these changes

2023-05-12 05:49 UTC, Nurbolot00 approved these changes

2023-05-12 05:50 UTC, dilmuratsarybaev approved these changes

2023-05-15 07:44 UTC, songhee24 requested changes

2023-05-15 07:44 UTC, songhee24 commented on src/api/infographics/infographicsService.ts
> +export default {
для сервисов лучше используйте export const

2023-05-15 07:44 UTC, songhee24 commented on src/api/infographics/infographicsService.ts
> +export default {
без default

2023-05-15 07:44 UTC, songhee24 commented on src/components/admin/UI/table/Table.tsx
> +                  {hoveredId === row.subProductId ? (
<img width="922" alt="Screenshot 2023-05-13 at 14 18 31" src="https://github.com/peaksoft-school/gadgetarium-js8/assets/44497623/0250bc65-8639-4585-b0ec-6793335a657d">

2023-05-15 07:44 UTC, songhee24 commented on src/components/admin/UI/table/Table.tsx
> +                  {hoveredId === row.subProductId ? (
при hover'е сильные подергивания

2023-05-15 07:44 UTC, songhee24 commented on src/api/instances.ts
> +      config.headers.Authorization = `Bearer${token}`
у вас бекенд без токена работает, оч странно)))
между ними проблем поставьте в любом случае
Bearer${token} => Bearer ${token}

2023-05-15 07:44 UTC, songhee24 commented on src/components/admin/product-infographics/Infographics.tsx
> +          <FirstAmount>{infographicsData.countRedeemed} шт</FirstAmount>
if infographicsData == undefined ?

2023-05-15 07:44 UTC, songhee24 commented on src/components/admin/product-infographics/InfographicsTab.tsx
> +function TabPanel(props: TabPanelProps) {
TabPanel переместите пожалуйста в отдельный файл

2023-05-15 07:44 UTC, songhee24 commented on src/components/admin/tab-components/AllProducts.tsx
> +  const columns: Column<Product>[] = [
useMemo use please

2023-05-15 07:44 UTC, songhee24 commented on src/components/admin/tab-components/AllProducts.tsx
> +          page={products.currentPage}
what if products == undefined ? or products == null ?

2023-05-15 07:44 UTC, songhee24 commented on src/components/admin/UI/table/Table.tsx
> +                      onClick={() => deleteHandler(row.subProductId)}
удалить не выходит ошибка с бека 
это ладно но если удалить не получилось нужно показывать ошибку в виде поп апа

2023-05-15 07:44 UTC, songhee24 commented on src/components/admin/UI/table/Table.tsx
> +                  {hoveredId === row.subProductId ? (
![Screenshot 2023-04-29 at 13 34 58](https://github.com/peaksoft-school/gadgetarium-js8/assets/44497623/55348f53-322a-4d23-a12a-cc507e533d88)
плюс если я выбрал продукт и убрал мышку он не должен пропадать а оставаться выбранным

2023-05-15 07:44 UTC, songhee24 commented on src/containers/admin/products/ProductsPage.tsx
> +            <InputBase
![Screenshot 2023-04-29 at 13 39 30](https://github.com/peaksoft-school/gadgetarium-js8/assets/44497623/d1f96079-cf27-4aab-a3d5-4dc633cf6418)

2023-05-15 07:44 UTC, songhee24 commented on src/containers/admin/products/ProductsPage.tsx
> +  const handleStartDateChange = (start: Date) => {
http://ec2-52-28-80-102.eu-central-1.compute.amazonaws.com/api/admin/products?status=%D0%92%D1%81%D0%B5+%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D1%8B&page=1&pageSize=7&from=2023-04-29&before=2023-04-28
пытался отправить запрос с датами вернул ошибку 
exceptionClassName
: 
"BadRequestException"
httpStatus: "BAD_REQUEST"
message: "The from date must be earlier than the date before"

нужно обрабатывать ошибки и показывать их

2023-05-15 07:44 UTC, songhee24 commented on src/hooks/pagination/usePagination.ts
> +export const useClientSidePagination = () => {
пагинация на будущее должна быть связана с беком

2023-05-16 13:46 UTC, songhee24 approved these changes

2023-05-16 13:46 UTC, merged