product-inner-page-and-details
peaksoft-school/gadgetarium-js8 pull request #36
Opened 2023-05-15 12:11 UTC by Nurbolot00

2023-06-01 08:06 UTC, FeruzaKazakova approved these changes

2023-06-01 08:07 UTC, myktybek03 approved these changes

2023-06-01 10:39 UTC, dilmuratsarybaev approved these changes

2023-06-02 08:31 UTC, songhee24 requested changes

2023-06-02 08:31 UTC, songhee24 commented on src/components/UI/preview-slider/PreviewSlider.tsx
> +        {images.map((image) => (
может проверку на то что фотки не найдены было бы лучше внутри этой компоненты делать

2023-06-02 08:31 UTC, songhee24 commented on src/components/admin/AdminHeader.tsx
>      navigate('/login')
navigate и replace ему нужно

2023-06-02 08:31 UTC, songhee24 commented on src/components/admin/UI/modals/CommentModal.tsx
> +      console.log(error)
у вас же есть notify почему бы его не использовать не надо просто в console.log оставлять  ошибки

2023-06-02 08:31 UTC, songhee24 commented on src/components/admin/product-inner-page/DetailsTable.tsx
> +          {paginate(rows).map((row, index) => {
Эх неужели в бекенде нет пагинации для деталей товара

2023-06-02 08:31 UTC, songhee24 commented on src/components/admin/product-inner-page/DetailsTable.tsx
> +          <Pagination
![Screenshot 2023-06-06 at 14 07 12](https://github.com/peaksoft-school/gadgetarium-js8/assets/44497623/bb085a91-40d5-4b1a-8215-7832b7fefaa6) 
ладно если пагинация клиентская то хотя бы это уберите если товаров мало

2023-06-02 08:31 UTC, songhee24 commented on src/containers/admin/product-inner-page/ProductInfo.tsx
> +            <StyledButton onClick={handleDownload}>
может сделать его отдельной компонентой

2023-06-02 08:31 UTC, songhee24 commented on src/components/admin/UI/modals/CommentModal.tsx
> +      console.log(error)
здесь тоже ввобще в принципе везде

2023-06-02 08:31 UTC, songhee24 commented on src/containers/admin/product-inner-page/ProductInfo.tsx
> +      console.log(error)
error

2023-06-02 08:31 UTC, songhee24 commented on src/containers/admin/product-inner-page/ProductInfo.tsx
> +                </Button>
![Screenshot 2023-06-06 at 14 21 33](https://github.com/peaksoft-school/gadgetarium-js8/assets/44497623/c7186ea2-3d73-4ed8-90b0-0ad4558a2e6e)
по идее нужно было сделать так чтобы
бэкенд отправлять количество всех отзывов чтобы не рендерить эту кнопку "Показать еще"
иначе постоянно спамят

2023-06-02 08:31 UTC, songhee24 commented on src/containers/admin/product-inner-page/ProductInfo.tsx
> +                </Button>
и запросы идут постоянно

2023-06-10 20:05 UTC, songhee24 approved these changes

2023-06-10 20:05 UTC, songhee24 commented on src/containers/admin/product-inner-page/ProductDetails.tsx
> +              onClick={async () => {
try catch

2023-06-10 20:05 UTC, songhee24 commented on src/containers/admin/product-inner-page/ProductInnerPage.tsx
> +      if (isAxiosError(e)) {
было бы классно создать отдельную helper функцию для isAxiosError

2023-06-10 20:05 UTC, merged