Feature/feedback
peaksoft-school/gadgetarium-js8 pull request #37
Opened 2023-05-25 12:09 UTC by dilmuratsarybaev

2023-05-25 12:52 UTC, FeruzaKazakova approved these changes

2023-05-25 13:07 UTC, myktybek03 approved these changes

2023-05-25 13:45 UTC, Nurbolot00 approved these changes

2023-05-29 10:53 UTC, songhee24 requested changes

2023-05-29 10:53 UTC, songhee24 commented on src/components/admin/reviews/RowTable.tsx
> +    dispatch(deleteReviewById(reviewData))
![Screenshot 2023-05-29 at 16 42 51](https://github.com/peaksoft-school/gadgetarium-js8/assets/44497623/079e3b02-8018-49a2-8ade-60964be84585)
после удаления модалка жавышыл керек

2023-05-29 10:53 UTC, songhee24 commented on src/components/admin/reviews/RowTable.tsx
> +              {item.answer ? (
нельзя ли более понятным образом сделать это ?

2023-05-29 10:53 UTC, songhee24 commented on src/components/admin/reviews/RowTable.tsx
> +                    <StyledButton onClick={updateHandleButtonClick}>Сохранить</StyledButton>
![Screenshot 2023-05-29 at 16 46 56](https://github.com/peaksoft-school/gadgetarium-js8/assets/44497623/f46b8093-3087-4796-a540-824c6e164f10)
answer пустой кетип калсак ошибка келтат 
ошибканы коргозуш керек же пустой кетире албайтурган кылыш керек

2023-05-29 10:53 UTC, songhee24 commented on src/components/admin/reviews/RowTable.tsx
> +  const [open, setOpen] = useState(false)
что за open для чего ? название понятным должно быть

2023-05-29 10:53 UTC, songhee24 commented on src/components/admin/UI/tabs/ReviewsTab.tsx
> +  const tabs = [
use memo

2023-05-30 07:02 UTC, songhee24 approved these changes

2023-05-30 07:02 UTC, merged