completed AdminAddProduct
peaksoft-school/gadgetarium-js8 pull request #38
Opened 2023-05-25 15:33 UTC by Nurzada03

2023-05-26 05:09 UTC, dilmuratsarybaev approved these changes

2023-05-26 07:01 UTC, FeruzaKazakova approved these changes

2023-05-29 11:12 UTC, songhee24 requested changes

2023-05-29 11:12 UTC, songhee24 commented on src/components/ReusableColorPicker.tsx
> +      {openColorPicker && <SketchPicker color={color} onChange={colorPickerHandler} />}
я говорил такое не рекомендуется писать только 
openColorPicker ? condition : null

2023-05-29 11:12 UTC, songhee24 commented on src/api/instances.ts
>  import axios from 'axios'
почему отдельный instance открыли у вас же уже есть

2023-05-29 11:12 UTC, songhee24 commented on src/App.tsx
> +  return <div></div>
как мне проверять зачем это нужно было делать ?

2023-05-29 11:12 UTC, songhee24 commented on src/components/admin/UI/addProduct/AddTabComponent.tsx
> +      console.log(error)
нет нет ошибку нужно показывать

2023-05-29 11:12 UTC, songhee24 commented on src/redux/store/addProduct/getCategories.thunk.ts
> +      if (isAxiosError(e)) {
ушул проверканы бир мтеод кылып койсонор болмок

2023-05-29 11:12 UTC, songhee24 commented on src/redux/store/addProduct/getCategories.thunk.ts
> +      if (isAxiosError(e)) {
постоянно повторяется

2023-05-29 11:12 UTC, songhee24 commented on src/utils/constants/theme/theme.ts
> +// export const palette: Color[] = [
что это еще такое

2023-05-29 11:12 UTC, songhee24 commented on src/utils/constants/types.ts
> +      colour: string
color

2023-05-29 11:12 UTC, songhee24 commented on src/App.tsx
> +  return <div></div>
да и через какой роутер мне проверять вашу компоненту

2023-05-29 11:51 UTC, Nurzada03 commented on src/utils/constants/types.ts
> +      colour: string
агай бул backend ушундай жазган экен, swagger де ,

2023-05-30 08:46 UTC, songhee24 requested changes

2023-05-30 08:46 UTC, songhee24 commented on src/components/admin/UI/addProduct/AddTabComponent.tsx
> +      console.log(error)
нужно показывать ошибки пользователю

2023-05-30 08:46 UTC, songhee24 commented on src/components/admin/UI/addProduct/AddbrandModal.tsx
> +        console.log(error)
здесь тоже нужно ошибку показывать пользователю

2023-05-30 08:46 UTC, songhee24 commented on src/components/admin/UI/addProduct/addProductDetailes/categories/SmartWatchCategorie.tsx
> +          color={colorSmartWatch}
<img width="444" alt="Screenshot 2023-05-31 at 14 06 39" src="https://github.com/peaksoft-school/gadgetarium-js8/assets/44497623/67bc925b-ad6c-4963-8012-a9d21147f5eb">
чтобы цвет закрыть нужно нажимать обратно на выборку цвета
и чтобы открыть цвет нужно нажимать на выборку цветы

я думаю было бы хорошо закрывать цвет когда нажимаешь на бэкдроп то есть как у модалки 
и нужно открывать выборку цвета когда нажимаешь на инпут цвета

2023-05-30 08:46 UTC, songhee24 commented on src/components/admin/UI/addProduct/addProductDetailes/categories/SmartphoneCategorie.tsx
> +        <ImagePicker onSelectImage={handlerImage} />
<img width="515" alt="Screenshot 2023-05-31 at 14 38 47" src="https://github.com/peaksoft-school/gadgetarium-js8/assets/44497623/7aa3047f-7d25-4bde-8ba0-78c1e8dd1fb1">
при добавлении фотографии можно выбрать несколько фотографии

2023-05-30 08:46 UTC, songhee24 commented on src/components/admin/UI/addProduct/AddTabComponent.tsx
> +              <StyledTextAddProduct>Добавить продукт</StyledTextAddProduct>
добавить продукт не отправляет запрос и не сохраняет продукт в бекенд а почему ?

2023-06-22 11:05 UTC, merged