Feature/basket
peaksoft-school/gadgetarium-js8 pull request #42
Opened 2023-06-02 13:19 UTC by dilmuratsarybaev

2023-06-02 14:09 UTC, FeruzaKazakova approved these changes

2023-06-10 20:19 UTC, songhee24 requested changes

2023-06-10 20:19 UTC, songhee24 commented on src/components/UI/tooltip/CustomTooltip.tsx
> +    <>
fragment don't need it

2023-06-10 20:19 UTC, songhee24 commented on src/components/user/basket/Basket.tsx
> +          <ContainerButton>
<img width="889" alt="Screenshot 2023-06-11 at 02 16 25" src="https://github.com/peaksoft-school/gadgetarium-js8/assets/44497623/7a508e2b-2804-4e70-9ffb-3cf830da1ce9">
Может нужно чтобы он немного ближе к окну располагался

2023-06-10 20:19 UTC, songhee24 commented on src/components/user/basket/BasketItem.tsx
> +          message: 'Товар успешно добавлен в избранное!',
removeByIdBasket болуп турат почемму Товар успешно добавлен в избранное!', ?

2023-06-10 20:19 UTC, songhee24 commented on src/components/user/basket/BasketItem.tsx
> +                    disabled={item.quantityProduct <= 1}
почему если товар равен = 1 то отключаем логику удаления для чего это ?

2023-06-12 16:23 UTC, songhee24 approved these changes

2023-06-12 16:23 UTC, merged