radio_checkbox
peaksoft-school/gadgetarium-js8 pull request #7
Opened 2023-04-06 14:57 UTC by dilmuratsarybaev

2023-04-07 10:14 UTC, FeruzaKazakova approved these changes

2023-04-07 10:14 UTC, FeruzaKazakova commented on tsconfig.json
>  }
no comments

2023-04-07 10:16 UTC, Nurzada03 approved these changes

2023-04-07 10:16 UTC, Nurzada03 commented on tsconfig.json
>      "jsx": "react-jsx"
good

2023-04-07 11:29 UTC, songhee24 requested changes

2023-04-07 11:29 UTC, songhee24 commented on src/components/UI/button/CheckBoxSuccess.tsx
> +export const CheckBoxSucces = ({ checked, onChange, label }: CheckBox) => {
<img width="148" alt="Screenshot 2023-03-29 at 17 26 51" src="https://user-images.githubusercontent.com/44497623/230601328-05c93aa7-869b-4688-8891-d7b4300b9092.png">
разные иконки
<img width="76" alt="Screenshot 2023-03-29 at 17 27 20" src="https://user-images.githubusercontent.com/44497623/230601356-26f90e11-5b66-41ac-ae79-826cfb9419cf.png">

2023-04-07 11:29 UTC, songhee24 commented on src/components/UI/button/CheckBox.tsx
> +export const CheckBoxLabels = ({ checked, onChange, label }: CheckBox) => {
<img width="109" alt="Screenshot 2023-03-29 at 17 27 54" src="https://user-images.githubusercontent.com/44497623/230601414-f81e4478-4258-4d4b-93f7-e690c613e8b0.png">
по дизайну разные иконки

2023-04-07 11:29 UTC, songhee24 commented on src/components/UI/button/CheckBox.tsx
> +const StyledCheckBox = styled(Checkbox)(() => ({
есть смысл открывать де компоненты для одного чекбокса у которого просто цвет меняется

2023-04-11 08:27 UTC, songhee24 approved these changes

2023-04-11 08:28 UTC, merged