done reusable-button
peaksoft-school/gadgetarium-js8 pull request #9
Opened 2023-04-08 12:14 UTC by myktybek03

2023-04-08 12:33 UTC, Nurzada03 requested changes

2023-04-08 12:33 UTC, Nurzada03 commented on src/components/UI/buttons/Button.tsx
> +      <MuiButtonStyled onClick={onClick} disabled={disabled} variant={variant} {...props}>
...props, type бериш керек

2023-04-09 08:48 UTC, Nurzada03 approved these changes

2023-04-09 12:07 UTC, Nurbolot00 approved these changes

2023-04-10 02:55 UTC, FeruzaKazakova approved these changes

2023-04-10 02:55 UTC, FeruzaKazakova commented on src/components/UI/buttons/Button.tsx
> +export default Button
no comments

2023-04-11 10:19 UTC, songhee24 requested changes

2023-04-11 10:19 UTC, songhee24 commented on src/components/UI/buttons/Button.tsx
> +    <div>
why div

2023-04-11 15:13 UTC, merged